name: Build & Publish Plugin

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build Plugin
        run: ./gradlew buildPlugin


      - name: Sign Plugin
        run: ./gradlew signPlugin

      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        run: ./gradlew publishPlugin